<a href="https://colab.research.google.com/github/axton123/Data_Science-Lab/blob/main/10_02_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB, BernoulliNB, CategoricalNB
from sklearn.metrics import confusion_matrix, accuracy_score

iris = datasets.load_iris()

x, y = iris.data[:,:], iris.target
x_tr, x_te, y_tr, y_te = train_test_split(x, y, stratify = y, random_state = 0, train_size = 0.7)

sc = StandardScaler()
x_tr = sc.fit_transform(x_tr)
x_te = sc.transform(x_te)

scores = []
classifier = GaussianNB()
classifier.fit(x_tr, y_tr)

y_pred = classifier.predict(x_te)
scores.append(accuracy_score(y_te,y_pred))
cm = confusion_matrix(y_te, y_pred)
print(cm)

print("\n")
classifier1 = BernoulliNB()
classifier1.fit(x_tr, y_tr)
y_pred = classifier.predict(x_te)
scores.append(accuracy_score(y_te, y_pred))
cm = confusion_matrix(y_te, y_pred)
print(cm)

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


step2


In [ ]:
from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus

data = load_iris()
print(data,data.shape)
print('class to predict: ', data.targrt_name)
print('Features : ', data.feature_names)