<a href="https://colab.research.google.com/github/axton123/Data_Science-Lab/blob/main/21_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from scipy.linalg import svd

A = array([[1,2],[3,4],[5,6]])
print("matrix  \n%s\n" %A)

u,s,vt = svd(A)
print("U:\n%s\n"%u)
print("S:\n%s\n"%s)
print("VT:\n%s\n"%vt)

kNN

In [ ]:
from sklearn import datasets, preprocessing
from sklearn.datasets import load_iris

iris = load_iris()
# print(iris)
print(iris.feature_names)
print("\n")
print(iris.target)
print("\n")
print(iris.target_names)
print("\n")
print(iris.data.shape)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


['setosa' 'versicolor' 'virginica']


(150, 4)


In [ ]:
from sklearn.model_selection import train_test_split
x, y = iris.data[:,:],iris.target
x_tr, x_te, y_tr, y_te = train_test_split(x, y, stratify = y, random_state = 0, train_size = 0.7)

print("\nshape of train and test x :\n\n")
print(x_tr.shape)
print(x_te.shape)

print("\n\nshape of train and test y :\n\n")
print(y_tr.shape)
print(y_te.shape)

scaler = preprocessing.StandardScaler().fit(x_tr)
x_tr = scaler.transform(x_tr)
x_te = scaler.transform(x_te)
print("\nscaled data\n")
print(x_tr)
print("\n\n")
print(x_te)


27/01/22

step 3:

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

scores = []
k_range = range(1,15)

for k in k_range:
  knn = KNeighborsClassifier(n_neighbors = k)
  knn.fit(x_tr, y_tr)
  y_pred = knn.predict(x_te)


print("prediction :\n {}".format(y_pred))
print("\naccuracy : ")
print(accuracy_score(y_te,y_pred))
print("\nconfusion mat : ")
print(confusion_matrix(y_te,y_pred))
print("\nclassfication : ")
print(classification_report(y_te,y_pred))

prediction :
 [2 2 0 0 1 0 1 1 0 1 0 2 0 2 1 1 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 1 1
 0 0 1 0 2 0 0 2]

accuracy : 
0.9333333333333333

confusion mat : 
[[15  0  0]
 [ 0 15  0]
 [ 0  3 12]]

classfication : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.83      1.00      0.91        15
           2       1.00      0.80      0.89        15

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45

