<a href="https://colab.research.google.com/github/axton123/Data_Science-Lab/blob/main/DS_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("abcd")

ds lab

In [2]:
import numpy as np

a = np.array([1,2,3])
print("%s" %type(a))
print("%s" %a.shape)

print(a)
print(a[0],a[1],a[2])
a[0]=5
print(a)


<class 'numpy.ndarray'>
3
[1 2 3]
1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])

print("\nShape of b:",b.shape)

print(b[0,0],
      b[0,1],
      b[1,0])

In [ ]:
a = np.zeros((3,2))
print("ALL zeros:\n%s"%a)

b = np.ones((2,2))
print("\nOnes mat:\n%s"%b)

d = np.eye(5)
print("\nidentity mat:\n%s"%d)

In [9]:
e = np.random.random((2,2))
print("\n random matrix: \n%s\n" %e)

print("vectorized sum example \n")
x = np.array([[1,2],[3,4]])
print("x:\n %s" %x)
print("sum: %s" %np.sum(x))
print("sum axis = 0 %s" %np.sum(x, axis=0))
print("sum axis = 1 %s" %np.sum(x, axis=1))


 random matrix: 
[[0.4497619  0.40958875]
 [0.26705219 0.13800319]]

vectorized sum example 

x:
 [[1 2]
 [3 4]]
sum: 10
sum axis = 0 [4 6]
sum axis = 1 [3 7]


In [7]:
a = np.arange(5)
b = np.arange(5)
print(a"\n")
dp = np.dot(a,b)
print("dot product: %s\n" %dp)
op = np.outer(a,b)
print("\n outer product: %s\n" %op)
ep = np.multiply(a,b)
print("\n element wise product: %s \n" %ep)

[0 1 2 3 4]
dot product: 30


 outer product: [[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


 element wise product: [ 0  1  4  9 16] 

